### PR TITLE
Fix timer tableview reloading

### LINKED ISSUE #4: Fix timer from reloading worldClockTableView

### PR DESCRIPTION
**Pull request by suhooh**
It fixes #4 and #3

### CODE REVIEW

File: Valencia/WorldClockViewController.swift [hunk 1]
```diff
@@ -27,7 +27,15 @@ class WorldClockViewController: UIViewController, UITableViewDelegate, UITableVi
   override func viewWillAppear(_ animated: Bool) {
     super.viewWillAppear(animated)
     loadCities()
-    timer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true, block: { _ in self.worldClockTableView.reloadData() })
+    timer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true, block: { [weak self] _ in
+      guard let indexPaths = self?.worldClockTableView.indexPathsForVisibleRows else { return }
```
Comment (jagpavv) [inline Valencia/WorldClockViewController.swift:31]: great job!

**Review by jagpavv — APPROVED** [review]
